import { quickSand, splineSans } from './fonts/fonts'
import './globals.css'
import { Bg } from '@/components/bg'
import { Header } from '@/components/header'
import clsx from 'clsx'
import type { Metadata } from 'next'
import { NuqsAdapter } from 'nuqs/adapters/next/app'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='es'>
			<body className={clsx(quickSand.variable, splineSans.variable, 'font-sans text-white antialiased')}>
				<NuqsAdapter>
					<div className='px-4'>
						<Bg />
						<Header />
						{children}
					</div>
				</NuqsAdapter>
			</body>
		</html>
	)
}
