import { quickSand, splineSans } from './fonts/fonts'
import './globals.css'
import clsx from 'clsx'
import type { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='es'>
			<body className={clsx(quickSand.variable, splineSans.variable, 'font-sans text-white antialiased')}>
				{children}
			</body>
		</html>
	)
}
